---
title: "P8105 Data Science I - Homework 5"
author: "Heng Hu (hh2648)"
date: 2025-11-08
output: github_document
---

```{r, message = FALSE}
# Setup
library(tidyverse)
set.seed(2648)
```


## Problem 1

```{r}

# Setup
iter = 100 #10000

# Function to test if there are duplicate birthdays in the group of n people.

dob_dup = function(n) {
  
  dob = sample(1:365, n, replace = TRUE)
  dob_dup = any(duplicated(dob))
    
}

# Simulating 10000 times for each group size between 2 and 50 and compute the probabilities across sample sizes.

sim_dob_dup = expand_grid(
    sample_size = 2:50,
    iter = 1:iter
  ) |> 
  mutate(dob_dup_fl = map(sample_size, dob_dup)) |> 
  unnest(cols = dob_dup_fl) |> 
  group_by(sample_size) |> 
  summarise(prob = mean(dob_dup_fl))

sim_dob_dup |> 
  knitr::kable()

# Make a plot showing the probability as a function of group size.

sim_dob_dup |> 
  ggplot(aes(x = sample_size, y = prob)) +
  geom_point() +
  geom_line()

```

comments


## Problem 2

```{r}

# Setup

n = 30
sigma = 5
iter = 50

# Function for reporting mu hat and p value from t test.

my_ttest = function(mu) {
  
  x = rnorm(n = n, mean = mu, sd = sqrt(sigma))
  
  result = t.test(x, mu = 0, conf.level = 0.95) |> 
    broom::tidy() |> 
    select(estimate, p.value) |> 
    rename(mu_hat = estimate,
           p_value = p.value) |> 
    mutate(reject_h0 = ifelse(p_value < 0.05, TRUE, FALSE))
  
}

# Simulating 5000 times for mu from 1 to 6.

sim_ttest = expand_grid(
    mu = 0:6,
    iter = 1:iter
  ) |> 
  mutate(ttest = map(mu, my_ttest)) |> 
  unnest(cols = ttest)

# Make a plot showing the proportion of times the null was rejected.

sim_ttest |> 
  group_by(mu) |> 
  summarise(prop = mean(reject_h0)) |> 
  ggplot(aes(x = mu, y = prop)) +
  geom_point() +
  geom_line()

```

comment

```{r}

# Make a plot showing the average estimate of mu hat in all samples and only in samples for which the null was rejected.

sim_ttest |> 
  mutate(mu_hat_h1 = ifelse(reject_h0, mu_hat, NA)) |> 
  group_by(mu) |> 
  summarise(avg_mu_hat_all = mean(mu_hat),
            avg_mu_hat_h1 = mean(mu_hat_h1, na.rm = TRUE)) |> 
  pivot_longer(cols = starts_with("avg_mu_hat"),
               names_to = "type",
               values_to = "avg_mu_hat",
               names_prefix = "avg_mu_hat_") |> 
  ggplot(aes(x = mu, y = avg_mu_hat, colour = type, shape = type)) +
  geom_point(alpha = 0.5, size = 4) +
  geom_line(alpha = 0.5)

```

comment

